### ISSUE TITLE
Bug: when already logged in, navigating to the root url in a new tab results in a blank page body.

### ISSUE THREAD

**Issue by dave-mills** [l-gorman/rhomis-data-app#6]
Steps to reproduce:

1. Log into the front-end app. 
2. Go to a new browser tab and enter the url to the root of the app. 

What should happen is the user gets redirected to 'home'. Instead, the user is directed to 'login', but as they are logged in by the time the page renders, nothing appears in the body: 

![CleanShot 2022-03-11 at 10 42 27](https://user-images.githubusercontent.com/5711101/157852139-8ed58d5e-7199-4461-9026-0ec836878619.png)

Notes:
From the console logs, it looks like RoutingComponent() is being run 3 times (I see 3 "Auth token context" messages). 

When in the same browser tab, it runs fine, likely as the app is already active and the authToken exists. But when navigating manually to a new tab, it looks like the first time the authToken is null - this causes the redirect to 'login'. The 2nd time, the authToken is correctly populated from the local storage, so my guess is that causes the login component to not render anything, but by that point we're past the point of redirecting the user?

**Comment by l-gorman** [comment]
Done a bit of exploring, problem is fixed now, also fixed a few other routing issues. Let me know if these work for you, if they work okay we can close this issue.

**Comment by dave-mills** [comment]
Looks like your update fixed the redirect-to-login issue - although now I'm getting redirected to home no matter what url I visit, e.g.: 

- https://app.l-gorman.com/#/projects/degm-2022/forms/degm-2022-1

Redirects me to home if I open it in a new tab (or come to that url from an external source, like the survey builder...). My guess is that the home redirect is overwriting all the requests?

**Comment by l-gorman** [comment]
I realised that yesterday afternoon and have found a fix. I have been making a whole series of changes to the app based on user feedback and it might be worth going through them all together before merging

**Comment by l-gorman** [comment]
This is still an issue @dave-mills, lets save this one for the sprint!!!
